I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 93, in script call
  File "game/scripts/script.rpy", line 93, in script call
ScriptError: could not find label 'dorm_scene_1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/glyphgryph/renpy-6.17.3-sdk/renpy/execution.py", line 294, in run
    node.execute()
  File "/home/glyphgryph/renpy-6.17.3-sdk/renpy/ast.py", line 1210, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "/home/glyphgryph/renpy-6.17.3-sdk/renpy/execution.py", line 371, in call
    return renpy.game.script.lookup(label)
  File "/home/glyphgryph/renpy-6.17.3-sdk/renpy/script.py", line 547, in lookup
    raise ScriptError("could not find label '%s'." % str(label))
ScriptError: could not find label 'dorm_scene_1'.

Linux-3.8.0-35-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.17.3.327
TwitchDatesPokemon 0.0
